### ISSUE TITLE
Создание pip пакета и его публикация

### ISSUE THREAD

**Issue by zmm** [OSLL/jabba#69]

**Comment by missingdays** [comment]
Отправил pull request #72 

Создал pip пакет, опубликовал в PyPi.

Для проверки
1. Установить пакет (возможно потребуется sudo)
```
pip install jabba
```

2. Из директории `maxscale-jenkins-jobs` запустить
```
jabba --yaml-root maxscale_jobs --analysis cyclic_deps
```
Убедиться, что программа отработала без ошибок.
