### ISSUE TITLE
Расширение режима анализа

### ISSUE THREAD

**Issue by missingdays** [OSLL/jabba#78]
Пользователь должен иметь возможность писать свои функции анализа и подключать их при запуске  jabba.

Подключать можно как отдельный `.py` файл, так и целый пакет, в котором пользователь определяет функции.

Написать мануал по созданию своих функций анализа.

**Comment by missingdays** [comment]
Отправил pull request #80 

Добавил возможность создавать свои функции анализа как в отдельном .py файле, так и целом модуле.

Написал мануал по созданию собственных функций анализа
https://github.com/OSLL/jabba/wiki/Analysis-extension
### Steps to reproduce
1. Обновить jabba

Из папки jabba
```
pip install . --upgrade --user
```

2. Запустить тест из файла

Из папки `maxscale-jenkins-jobs`
```
jabba --analysis dummy_check --export-analysis ../jabba/integration_tests_data/analysis_extensions/extension_test.py 
```
Убедиться, что выводится `OK`

3. Запустить тест из модуля
```
jabba --analysis dummy_check --export-analysis jabba_analysis
```

Убедиться, что выводится `OK`

**Comment by zmm** [comment]
vood@vood-ThinkPad:~/ws/maxscale-jenkins-jobs$ jabba --analysis dummy_check --export-analysis ../jabba/integration_tests_data/analysis_extensions/extension_test.py
usage: jabba [-h] [--files FILES [FILES ...]] [--include-graph] [--call-graph]
             [--yaml-root YAML_ROOT] [--call-display {none,text,edge}]
             [--rank-dir {left-right,up-down}]
             [--call-parameters CALL_PARAMETERS [CALL_PARAMETERS ...]]
             [--legend] [--config CONFIG] [--synonyms SYNONYMS [SYNONYMS ...]]
             [--name NAME] [--analysis ANALYSIS [ANALYSIS ...]]
             [--export-shell EXPORT_SHELL] [--verbose VERBOSE]
jabba: error: unrecognized arguments: --export-analysis ../jabba/integration_tests_data/analysis_extensions/extension_test.py

**Comment by missingdays** [comment]
Убедитесь, пожалуйста, что локальная установка jabba проходит без ошибок
```
sudo pip install . --upgrade --user
```

**Comment by zmm** [comment]
Евгений, поправьте пожалуйста конфликты

**Comment by missingdays** [comment]
Исправил, замерджил в мастер
